### ISSUE TITLE
电脑运行程序闪退

### ISSUE THREAD

**Issue by imlfc** [zqzess/Njtech-AutoLogin#1]
大佬好，我的电脑运行后报下面的错误，怎么办呀？
****************************Njtech校园网自动登录****************************
****************************author @ zqzess****************************
Traceback (most recent call last):
  File "autoLogin.py", line 35, in <module>
  File "configparser.py", line 696, in read
  File "configparser.py", line 1079, in _read
configparser.MissingSectionHeaderError: File contains no section headers.
file: './config.ini', line: 1
'\ufeff#UserInfo是定义账号信息\n'
[8568] Failed to execute script 'autoLogin' due to unhandled exception!

**Comment by zqzess** [comment]
你把那个config.ini提出来，就是移动另一个文件夹，然后运行程序，他会重新自动生成congfig.ini,然后再去新生成的config里面填写账号密码，用txt打开

**Comment by zqzess** [comment]
他运行完毕会自动退出的

**Comment by imlfc** [comment]
是的，其他电脑是了可以正常运行登录校园网，这台电脑运行后程序会报错误，是不是电脑缺少什么环境呀？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月18日(周二) 晚上6:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zqzess/Njtech-AutoLogin] 电脑运行程序闪退 (Issue #1)




 
他运行完毕会自动退出的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by imlfc** [comment]
我再试一一下，刚才没看到这条🌝



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月18日(周二) 晚上6:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zqzess/Njtech-AutoLogin] 电脑运行程序闪退 (Issue #1)




 
你把那个config.ini提出来，就是移动另一个文件夹，然后运行程序，他会重新自动生成congfig.ini,然后再去新生成的config里面填写账号密码，用txt打开
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by imlfc** [comment]
大佬，问题解决了，是记事本编码的问题，用其他的电脑编辑好config.ini，然后拖入这个电脑后就可以正常运行了。

**Comment by zqzess** [comment]
我感觉也是编码问题，但是拿程序自动生成的再用txt打开它应该会默认utf8
