### ISSUE TITLE
bash和openwrt版均无法正常工作

### ISSUE THREAD

**Issue by Marztop** [zqzess/Njtech-AutoLogin#3]
openwrt版本会重复修改login.sh中的insert_cookie，导致出现两行-H进行cookie传递。

我修改之后，login.sh中的参数能对得上，但curl后依然无法联网，返回为空，不清楚是否新学期参数数量有变化。

runlog.txt:

HTTP/1.1 302 Found
Server: Apache-Coyote/1.1
Pragma: no-cache
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: no-cache
Cache-Control: no-store
Location: /cas/login?service=https%3A%2F%2Fu.njtech.edu.cn%2Foauth2%2Fauthorize%3Fclient_id%3DOe7wtp9CAMW0FVygUasZ%26response_type%3Dcode%26state%3Dnjtech%26s%3Df682b396da8eb53db80bb072f5745232
Content-Length: 0
Date: Fri, 16 Sep 2022 09:02:03 GMT

我也试过将变量放进-data-raw改为json形式传参，但是传参失败，一直返回登录页面
两个脚本我在路由器和电脑上都试过了，都没法工作
路由器固件版本PandoraBox R8.1.12 ， 电脑Ubuntu20.04

**Comment by zqzess** [comment]
bash版是哪个，shell那个吗，那个是macos的，linux环境不一样，pandorabox没用过，openwrt上运行时可以使用的，openwrt理论上兼容ubuntu，你可以看一下这个[Issues](https://github.com/zqzess/Njtech-AutoLogin/issues/2)

目前的话，njtech-home自动认证是正常的，njtech不可用，认证已经改变且支持无感登陆了，无需自动登录

然后302也不是就一定是错的，网络是否连通可以测试一下百度

固件是pandorabox的话，有点小众建议尝试自己改写一下

至于ubuntu运行失败，过几天我开个虚拟机测试一下，昨天电脑刚重置这两天在装环境
